[package]
name = "eatmem"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[package.metadata.build-package]
source-groups = [ "eatmem" ]

[lib]
path = "../packages.rs"

# RPM BuildRequires
[build-dependencies]
glibc = { path = "../glibc" }
